### ISSUE TITLE
unable to sell-all to npc

### ISSUE THREAD

**Issue by Almeida1103** [Vithrax/vBot#3]
actually when i make an script to sell all to npc, appears a yellow message sayng
"warn while executing cavebot action (sellall): [string"/vbot/net_cavebot_lib.lua"] :194: attempt to index local "name" (a nil value) " ... how can i fix this?

**Comment by Vithrax** [comment]
fixed in https://github.com/Vithrax/vBot/commit/4cb7c3d0139cc512bbcb28ef3cd4c5cb9f09f3b7
